--------------------------------------------------------
--  File created - Monday-November-06-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMPANY
--------------------------------------------------------

  CREATE TABLE "SAMPLE_RJ"."COMPANY" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(10 BYTE), 
	"CODE" VARCHAR2(5 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTACT
--------------------------------------------------------

  CREATE TABLE "SAMPLE_RJ"."CONTACT" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"BIRTHDAY" DATE, 
	"VIPYN" NUMBER(1,0) DEFAULT 0, 
	"COMPANYID" VARCHAR2(5 BYTE), 
	"CONTACT_NUMBER" VARCHAR2(11 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence COMPANY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SAMPLE_RJ"."COMPANY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CONTACT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SAMPLE_RJ"."CONTACT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into SAMPLE_RJ.COMPANY
SET DEFINE OFF;
Insert into SAMPLE_RJ.COMPANY (ID,NAME,CODE,DESCRIPTION) values (21,'Lotus Labs','LOTUS','The leading software development company in online gaming');
REM INSERTING into SAMPLE_RJ.CONTACT
SET DEFINE OFF;
Insert into SAMPLE_RJ.CONTACT (ID,NAME,BIRTHDAY,VIPYN,COMPANYID,CONTACT_NUMBER) values (22,'Cedric',to_date('12-DEC-17','DD-MON-RR'),1,'LOTUS','00000000000');
Insert into SAMPLE_RJ.CONTACT (ID,NAME,BIRTHDAY,VIPYN,COMPANYID,CONTACT_NUMBER) values (31,'rj',to_date('12-DEC-17','DD-MON-RR'),1,'LOTUS','1111111110');
--------------------------------------------------------
--  DDL for Index NAME_P_KEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAMPLE_RJ"."NAME_P_KEY" ON "SAMPLE_RJ"."CONTACT" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CODE_P_KEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAMPLE_RJ"."CODE_P_KEY" ON "SAMPLE_RJ"."COMPANY" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMPANY
--------------------------------------------------------

  ALTER TABLE "SAMPLE_RJ"."COMPANY" ADD CONSTRAINT "CODE_P_KEY" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SAMPLE_RJ"."COMPANY" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "SAMPLE_RJ"."COMPANY" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTACT
--------------------------------------------------------

  ALTER TABLE "SAMPLE_RJ"."CONTACT" ADD CONSTRAINT "NAME_P_KEY" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SAMPLE_RJ"."CONTACT" MODIFY ("VIPYN" NOT NULL ENABLE);
  ALTER TABLE "SAMPLE_RJ"."CONTACT" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CONTACT
--------------------------------------------------------

  ALTER TABLE "SAMPLE_RJ"."CONTACT" ADD CONSTRAINT "CID_F_KEY" FOREIGN KEY ("COMPANYID")
	  REFERENCES "SAMPLE_RJ"."COMPANY" ("CODE") ENABLE;
